// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9djEQi9BlPhhH_k_abPCorcQ57hMhTxE',
    appId: '1:629550212071:web:4f08d4aed0c9301f7a1342',
    messagingSenderId: '629550212071',
    projectId: 'cambridgeenglishdictionaryfree',
    authDomain: 'cambridgeenglishdictionaryfree.firebaseapp.com',
    storageBucket: 'cambridgeenglishdictionaryfree.appspot.com',
    measurementId: 'G-41WMMLWPZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfmanI5IMvlmta13OCSAzbRShgledH-z4',
    appId: '1:629550212071:android:6c17b8e4d8183cc37a1342',
    messagingSenderId: '629550212071',
    projectId: 'cambridgeenglishdictionaryfree',
    storageBucket: 'cambridgeenglishdictionaryfree.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEimhC7FB62cj-lOzOkQls8Y6CfKhpFdU',
    appId: '1:629550212071:ios:78647db75f4499d47a1342',
    messagingSenderId: '629550212071',
    projectId: 'cambridgeenglishdictionaryfree',
    storageBucket: 'cambridgeenglishdictionaryfree.appspot.com',
    iosClientId: '629550212071-7i3utvm69i9nkb27p5aenoeabiem63pf.apps.googleusercontent.com',
    iosBundleId: 'com.siagofarova.cambridgeeglishdictionaryfree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEimhC7FB62cj-lOzOkQls8Y6CfKhpFdU',
    appId: '1:629550212071:ios:78647db75f4499d47a1342',
    messagingSenderId: '629550212071',
    projectId: 'cambridgeenglishdictionaryfree',
    storageBucket: 'cambridgeenglishdictionaryfree.appspot.com',
    iosClientId: '629550212071-7i3utvm69i9nkb27p5aenoeabiem63pf.apps.googleusercontent.com',
    iosBundleId: 'com.siagofarova.cambridgeeglishdictionaryfree',
  );
}
